### ISSUE TITLE
Finalise new release

### ISSUE THREAD

**Issue by afonsoguerra** [PGP-UK/GenomeChronicler#21]
- [ ] Ensure #19 is finalised
- [ ] Ensure #20 is finalised
- [ ] Fully test solution for #11 
- [ ] Create a new release on github with the latest database references
- [ ] Update the SetupMe.sh script to retrieve references and code from the github repository release similar to the Dockerfile
- [ ] Create new github release for the latest GenomeChronicler codebase
